-- MySQL Script generated by MySQL Workbench
-- Thu May  7 20:35:09 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema PlasticosDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PlasticosDB
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `PlasticosDB` DEFAULT CHARACTER SET utf8mb4;
SHOW WARNINGS;
USE `PlasticosDB` ;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`Category`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`Category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`Category` (
  `CategoryId` INT NOT NULL AUTO_INCREMENT,
  `CategoryName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(300) NULL,
  PRIMARY KEY (`CategoryId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`State`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`State` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`State` (
  `StateId` INT NOT NULL AUTO_INCREMENT,
  `StateName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StateId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`City`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`City` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`City` (
  `CityId` INT NOT NULL AUTO_INCREMENT,
  `CityName` VARCHAR(45) NOT NULL,
  `StateId` INT NOT NULL,
  PRIMARY KEY (`CityId`, `StateId`),
  CONSTRAINT `fk_City_State1`
    FOREIGN KEY (`StateId`)
    REFERENCES `PlasticosDB`.`State` (`StateId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`Product`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`Product` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`Product` (
  `ProductId` INT NOT NULL AUTO_INCREMENT,
  `ProductName` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(300) NULL,
  `Price` INT NOT NULL,
  `Amount` VARCHAR(25) NULL,
  `Brands` VARCHAR(60) NULL,
  `Material` VARCHAR(60) NULL,
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`User`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`User` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Lastname` VARCHAR(45) NULL,
  `Mail` VARCHAR(100) NOT NULL,
  `Password` VARCHAR(16) NOT NULL,
  `Address` VARCHAR(100) NULL,
  `Gender` ENUM('M,F,O') NULL,
  `Birthdate` DATE NULL,
  `Photo` BLOB NULL,
  `Permissions` ENUM('admin,user,editor') NOT NULL,
  `CityId` INT NULL,
  PRIMARY KEY (`UserId`),
  CONSTRAINT `fk_User_City1`
    FOREIGN KEY (`CityId`)
    REFERENCES `PlasticosDB`.`City` (`CityId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`Comment`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`Comment` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`Comment` (
  `CommentId` INT NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(400) NOT NULL,
  `Date` DATETIME NOT NULL,
  `ProductId` INT NOT NULL,
  `User_UserId` INT NOT NULL,
  PRIMARY KEY (`CommentId`),
  CONSTRAINT `fk_Product_has_User_Product2`
    FOREIGN KEY (`ProductId`)
    REFERENCES `PlasticosDB`.`Product` (`ProductId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_has_User_User2`
    FOREIGN KEY (`User_UserId`)
    REFERENCES `PlasticosDB`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`Company`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`Company` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`Company` (
  `CompanyId` INT NOT NULL AUTO_INCREMENT,
  `CompanyName` VARCHAR(50) NOT NULL,
  `PhoneNumber` VARCHAR(30) NULL,
  `MobileNumber` VARCHAR(30) NULL,
  `Email` VARCHAR(60) NULL,
  `AboutUs` VARCHAR(500) NULL,
  `Mission` VARCHAR(500) NULL,
  `Vision` VARCHAR(500) NULL,
  `Place` VARCHAR(45) NULL,
  `FrameLocation` VARCHAR(200) NULL,
  `CityId` INT NULL,
  PRIMARY KEY (`CompanyId`),
  CONSTRAINT `fk_Company_City1`
    FOREIGN KEY (`CityId`)
    REFERENCES `PlasticosDB`.`City` (`CityId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`Favorite`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`Favorite` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`Favorite` (
  `UserId` INT NOT NULL,
  `ProductId` INT NOT NULL,
  PRIMARY KEY (`UserId`, `ProductId`),
  CONSTRAINT `fk_Product_has_User_Product1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `PlasticosDB`.`Product` (`ProductId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_has_User_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `PlasticosDB`.`User` (`UserId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PlasticosDB`.`ProductXCategory`
-- -----------------------------------------------------
-- DROP TABLE IF EXISTS `PlasticosDB`.`ProductXCategory` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PlasticosDB`.`ProductXCategory` (
  `ProductId` INT NOT NULL,
  `CategoryId` INT NOT NULL,
  PRIMARY KEY (`ProductId`, `CategoryId`),
  CONSTRAINT `fk_Category_has_Product_Category1`
    FOREIGN KEY (`CategoryId`)
    REFERENCES `PlasticosDB`.`Category` (`CategoryId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Category_has_Product_Product1`
    FOREIGN KEY (`ProductId`)
    REFERENCES `PlasticosDB`.`Product` (`ProductId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
